version: "3.8"

services:
  backend:
    image: bgin86/backend
    container_name: backend
    ports:
      - "5000:5000"
    networks:
      - app-network

  frontend:
    image: bgin86/frontend
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
