version: "3.8"

services:
  backend:
    build:
      context: ./Backend
      dockerfile: ../Dockerfile.backend
    ports:
      - "8080:80"
    volumes:
      - ./Backend:/app
    networks:
      - app-network

  frontend:
    build:
      context: ./Frontend
    ports:
      - "3000:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
