version: "3.8"

services:
  backend:
    build:
      context: ./Backend
    image: bgin86/backend
    ports:
      - "5000:5000"
    networks:
      - app-network

  frontend:
    build:
      context: ./Frontend
    image: bgin86/frontend
    ports:
      - "8080:80"
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
