version: "3.8"

services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile.backend
    expose:
      - "5000"
    networks:
      - app-network

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile.frontend
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80" # ✅ Required: public access with no custom ports
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./Frontend/build:/usr/share/nginx/html:ro
    depends_on:
      - backend
      - frontend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
