# syntax=docker/dockerfile:1

FROM python:3.10-slim

WORKDIR /app

# Copy only what's needed
COPY backend/requirements.txt .

RUN pip install --upgrade pip && pip install -r requirements.txt

# Copy all application code (relative to Dockerfile)
COPY backend /server

CMD ["python", "server.py"] 

